# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='lobby',
            name='lobbyName',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
