# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 11:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegame',
            name='playerRoles',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'player_list': 1}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basegame',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lobby.Lobby'),
        ),
    ]
