# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 08:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20171027_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=-1)),
                ('setting', models.CharField(max_length=64)),
                ('visibility', django.contrib.postgres.fields.jsonb.JSONField()),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.BaseGame')),
            ],
        ),
    ]
