# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobbyName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('isPublic', models.IntegerField()),
                ('totalSlots', models.IntegerField()),
                ('occupiedSlots', models.IntegerField()),
            ],
        ),
    ]
