# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
