# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_auto_20171014_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='isPublic',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='occupiedSlots',
            field=models.IntegerField(default=1),
        ),
    ]
