# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lobby', '0003_auto_20171017_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='leader',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
