# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_auto_20171017_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
