# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_auto_20171018_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='key',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
    ]
