# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_lobby_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='key',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
